apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: yoshitakumi/voting-app-worker:latest
        env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_NAME
            value: "postgres"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: POSTGRES_PASSWORD
          - name: REDIS_HOST
            value: "redis-service"
